name = "warp"
main = "src/index.ts"
compatibility_date = "2023-08-23"

[[d1_databases]]
binding = "DATABASE"
database_name = "warp-db"
database_id = "11cd3cc3-1a5e-492a-a602-896e4bdb4186"

[triggers]
crons = [
    '* * * * *',
]

# 在这里定义你需要注入的变量
[vars]
LOSS_THRESHOLD = 10
DELAY_THRESHOLD = 500
RANDOM_COUNT = 10
GET_DATA_INTERVAL = 2
SAVE_ACCOUNT_INTERVAL = 10
RESET_ACCOUNT_INTERVAL = 2880
